### ISSUE TITLE
Enable structured colors with dynamic options

### ISSUE THREAD

**Issue by Benjamin-Bach** [sylvainjule/kirby-color-palette#17]
Hi Sylvain
Great job this plugin.
I'm trying to use dynamic options from a structured field.
For the color, it works, but the tooltip does not get the name.
What am I missing? 

My color-palette field:
```
type: color-palette
options: query
query:
   fetch: site.colors.toStructure
   value: "{{structureItem.color}}"
   tooltip: "{{structureItem.name}}"
```
My structured field:
```
label: Colors used within pages
type: structure
fields:
   name:
     type: text
     label: Name
   color:
     extends: fields/styles/color
```

Thank you
