### ISSUE TITLE
Any way to get the key of structured field?

### ISSUE THREAD

**Issue by macx** [sylvainjule/kirby-color-palette#5]
I'm using the structured version. Is there any way to get the key (for example "default" or "alternative") of the selected option?

Or is there an option to save the key and not the values? Then I could style my content within the stylesheet as theme instead of using inline styles.

My options:

```yaml
options:
  default:
    background: '#FFFFFF'
    text: '#3F3F3F'
  alternative:
    background: '#ECEFF1'
    text: '#3F3F3F'
  disruptor:
    background: '#0028DC'
    text: '#FFFFFF'
  laufcampus:
    background: '#25AB1C'
    text: '#FFFFFF'
```

Stored as:

```html
theme:
  background: '#ECEFF1'
  text: '#3F3F3F'
```

Would be nice to get:

```html
theme: alternative
```

If I set the key-value pair under background and text, I get what I want, but it's not automatic

```html
theme:
  background: '#ECEFF1'
  text: '#3F3F3F'
  key: alternative
```
