### ISSUE TITLE
Default source for extractor

### ISSUE THREAD

**Issue by nilshoerrmann** [sylvainjule/kirby-color-palette#8]
I just started experimenting with this really helpful field (thanks @sylvainjule!).
Using the `extractor` setting, is there a way to set a default source?

Let me give you some more context:

We are working on a project blueprint that features two image sections, one for a cover image and one for other images used inside the main copy. We'd like to extract colours from the cover only and the related section has a limit of one image. So either there is an image to extract from or there is none. And everytime there is one, we'd like to get the related colour palette.

So I was thinking of having a `template` option which would tell the plugin to automatically choose the first image with this template by default:

```yaml
colours:
  type: color-palette
  label: Colours
  extractor: true
  limit: 8
  template: cover
```

Is something like this already possible or is this an addition you might consider adding?
